use_frameworks!

platform :ios, '9.0'

target 'HeatMap_Example' do
  pod 'HeatMap', :path => '../'

  target 'HeatMap_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
